name: Pest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: xdebug
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Configure Laravel
        run: |
          cp .env.example .env
          touch database/database.sqlite
          php artisan key:generate
          php artisan jwt:secret
          php artisan migrate
      - name: Run Pest
        run: ./vendor/bin/pest --testdox-html pest-reports/pest_report.html
      - name: Save tests output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pest_report
          path: pest-reports/pest_report.html
